### ISSUE TITLE
Possible SQL injection

### ISSUE THREAD

**Issue by smokku** [jugglingdb/sqlite3-adapter#27]
https://github.com/jugglingdb/sqlite3-adapter/blob/168d534406/lib/sqlite3.js#L252 is:
    var sql = 'SELECT \* FROM ' + this.tableEscaped(model) + ' WHERE id = ' + id + ' LIMIT 1';

What happens when I call:
    User.find(model, '1; DROP TABLE users; --', function() {});

**Comment by 1602** [comment]
fixed!
