### ISSUE TITLE
Upsert removes fields not in data

### ISSUE THREAD

**Issue by Jon889** [jugglingdb/sqlite3-adapter#30]
If I have a schema with say id, name and location. And do .upsert({name:"new name"}, callback), then in the database the location value is deleted.  Surely if the field doesn't exist in the data object passed to upsert, then the value in the database shouldn't be changed.

**Comment by 1602** [comment]
It was broken by design of sqlite: http://stackoverflow.com/questions/418898/sqlite-upsert-not-insert-or-replace/4330694#4330694

Now broken method is removed so that jugglingdb fill fallback to default method which is basically find + update / create. No beautiful solution there yet.
