### ISSUE TITLE
Order by

### ISSUE THREAD

**Issue by coderazzi** [jugglingdb/sqlite3-adapter#34]
Current code doesn't allow for an expression in order:
Writing something like:
        {order: 'updated+year_4_365_86400000'}
Is translated into:
ORDER BY `updated+year_4_365_86400000`
which is wrong (the whole expression is taken as ONE identifier). 

The offending code is:
    function buildOrderBy(order) {
        if (typeof order === 'string') order = [order];
        return 'ORDER BY ' + order.map(function(o) {
            var t = o.split(/\s+/);
            if (t.length === 1) {
                return '`' + o + '`';
            }
            return '`' + t[0] + '` ' + t[1];
        }).join(', ');
    }

This code assumes very simple order clauses, such as identifier + DESC / ASC.

Reading this code, a workaround for my problem is to put a space after an identifier, like in:
 {order: 'updated +year_4_365*86400000'}

But any serious rewriting of the library will break this code.

**Comment by 1602** [comment]
I believe this has been fixed a long time ago.
